###############################################################################
# Auto-generated by `jupyter-book config`
# If you wish to continue using _config.yml, make edits to that file and
# re-generate this one.
###############################################################################
author = 'QDaria AS'
autodoc_default_options = {'members': True, 'undoc-members': True, 'show-inheritance': True}
autodoc_member_order = 'bysource'
autodoc_mock_imports = ['zipminator._core', 'faker', 'pyzipper', 'httpx', 'cryptography']
comments_config = {'hypothesis': False, 'utterances': False}
copybutton_prompt_is_regexp = False
copybutton_prompt_text = '$ '
copyright = '2023'
exclude_patterns = ['**.ipynb_checkpoints', '**/CLAUDE.md', '.DS_Store', 'Thumbs.db', '_build', 'content/appendix.md', 'content/intro.md']
extensions = ['sphinx_togglebutton', 'sphinx_copybutton', 'myst_nb', 'jupyter_book', 'sphinx_thebe', 'sphinx_comments', 'sphinx_external_toc', 'sphinx.ext.intersphinx', 'sphinx_design', 'sphinx_book_theme', 'sphinx.ext.autodoc', 'sphinx.ext.napoleon', 'sphinx.ext.viewcode', 'sphinx_jupyterbook_latex', 'sphinx_multitoc_numbering']
external_toc_exclude_missing = False
external_toc_path = '_toc.yml'
html_baseurl = ''
html_css_files = ['custom.css', 'custom.css']
html_favicon = '_static/Z.svg'
html_js_files = ['custom.js', 'custom.js']
html_logo = '_static/zipminator-logo-light.svg'
html_sourcelink_suffix = ''
html_static_path = ['_static']
html_theme = 'sphinx_book_theme'
html_theme_options = {'logo': {'image_light': '_static/zipminator-logo-dark.svg', 'image_dark': '_static/zipminator-logo-light.svg'}, 'repository_url': 'https://github.com/QDaria/zipminator', 'use_repository_button': True, 'use_issues_button': True, 'use_download_button': True, 'extra_footer': '<p><a href="https://www.zipminator.zip">zipminator.zip</a> | <a href="https://www.zipminator.zip/docs">Docs Overview</a> | <a href="https://qdaria.com">QDaria</a></p>', 'launch_buttons': {'colab_url': 'https://colab.research.google.com'}}
html_title = 'Zipminator'
latex_engine = 'pdflatex'
myst_enable_extensions = ['colon_fence', 'deflist', 'dollarmath', 'linkify', 'substitution', 'tasklist', 'html_image']
myst_url_schemes = ['mailto', 'http', 'https']
napoleon_google_docstring = True
napoleon_include_init_with_doc = True
napoleon_numpy_docstring = True
nb_execution_allow_errors = False
nb_execution_cache_path = ''
nb_execution_excludepatterns = ['notebooks/10_*', 'notebooks/Untitled*']
nb_execution_in_temp = False
nb_execution_mode = 'auto'
nb_execution_timeout = 180
nb_mime_priority_overrides = [['application/vnd.plotly.v1+json', 'text/html', 0]]
nb_output_stderr = 'show'
nb_render_image_options = {'width': '100%'}
numfig = True
pygments_style = 'sphinx'
suppress_warnings = ['autodoc', 'autodoc.import_object']
use_jupyterbook_latex = True
use_multitoc_numbering = True
