default_platform(:ios)

platform :ios do
  desc "Build and upload a new beta build to TestFlight"
  lane :beta do
    setup_ci if ENV["CI"]

    app_store_connect_api_key(
      key_id: ENV["ASC_API_KEY_ID"],
      issuer_id: ENV["ASC_API_KEY_ISSUER_ID"],
      key_content: ENV["ASC_API_KEY_CONTENT"],
      is_key_content_base64: true,
      in_house: false,
    )

    match(type: "appstore", readonly: true)

    Dir.chdir("../..") do
      sh("flutter", "build", "ipa", "--release", "--export-method=app-store")
    end

    ipa_path = Dir["../build/ios/ipa/*.ipa"].first
    UI.user_error!("No .ipa produced by flutter build ipa") if ipa_path.nil?

    pilot(
      ipa: ipa_path,
      skip_waiting_for_build_processing: true,
      api_key_path: nil,
    )
  end
end
