#!/usr/bin/env bash
# stage-human-actions.sh — assemble drafts/runbooks for human-gated tracks.
# Produces NO secrets and performs NO external submissions. It only collects the
# exact steps/commands/payloads the USER will execute, into docs/guides/program/runbooks/.
# Per the plan: agents prep & stage; the user executes.
#
# Usage: stage-human-actions.sh --track <ID>
set -euo pipefail
ROOT="${ZIPMINATOR_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
TRACK=""
while [ $# -gt 0 ]; do case "$1" in --track) TRACK="$2"; shift 2;; *) echo "unknown arg $1" >&2; exit 1;; esac; done
[ -n "$TRACK" ] || { echo "usage: $0 --track <ID>" >&2; exit 1; }

OUT="$ROOT/docs/guides/program/runbooks"
mkdir -p "$OUT"
RB="$OUT/${TRACK}-runbook.md"
log() { printf '\033[33m[stage:%s]\033[0m %s\n' "$TRACK" "$*"; }

# Guard: never let a secret value land in a runbook. Names/placeholders only.
emit() { printf '%s\n' "$*" >> "$RB"; }

: > "$RB"
emit "# Human-action runbook — Track $TRACK"
emit "_Generated by stage-human-actions.sh. Placeholders only; no live secrets. You execute these._"
emit ""

case "$TRACK" in
  A)
    emit "## Waitlist pipeline (Supabase + Resend)"
    emit '1. Run migration on prod Supabase: apply `web/supabase/migrations/0001_waitlist.sql`.'
    emit '2. Mint NEW Supabase keys (project uogbyl…); set in Vercel + local `web/.env.local`:'
    emit '   - `NEXT_PUBLIC_SUPABASE_URL`, `NEXT_PUBLIC_SUPABASE_ANON_KEY` (or publishable), `SUPABASE_SERVICE_ROLE_KEY`'
    emit '3. Create a Resend API key, set `RESEND_API_KEY` in Vercel; verify `qdaria.com` SPF/DKIM in Resend.'
    emit '4. `vercel env add` for each (production + preview), then redeploy.'
    emit '5. Verify: `curl https://www.zipminator.zip/api/waitlist` → `supabase: configured`; submit the form → 200 + row + email.'
    ;;
  E)
    emit "## iOS TestFlight secrets (code already parameterised)"
    emit '1. Create private certs repo `QDaria/certificates` (empty, private).'
    emit '2. `cd app/ios && bundle exec fastlane match init` (seed appstore cert/profile for com.qdaria.zipminator).'
    emit '3. Register GitHub Actions secrets (names only): `ASC_API_KEY_ID`, `ASC_API_KEY_ISSUER_ID`, `ASC_API_KEY_CONTENT`, `MATCH_GIT_URL`, `MATCH_PASSWORD`, `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD`, plus env `ITC_TEAM_ID`.'
    emit '4. Tag a build on reconciled main to trigger `.github/workflows/testflight.yml`.'
    ;;
  I)
    emit "## Android keystore + Play upload"
    emit '1. Generate upload keystore; populate `app/android/key.properties` from `key.properties.example` (never commit).'
    emit '2. `flutter build appbundle --release`; `bundletool` dry-run validate.'
    emit '3. Upload AAB to Play Console internal testing.'
    ;;
  D)
    emit "## PyPI publish (OIDC trusted publishing — no token)"
    emit '1. After T0 reconcile lands on main: `git tag -a v0.5.1 -m "zipminator 0.5.1" && git push origin v0.5.1`.'
    emit '2. Approve the `pypi` GitHub Environment deployment if required reviewers are set.'
    emit '3. Verify: `pip install zipminator==0.5.1`.'
    ;;
  G)
    emit "## Papers — Zenodo deposit + venue lane"
    emit '1. Log in to Zenodo via ORCID; reserve 3 DOIs; populate Related Identifiers; upload the 3 PDFs; Publish.'
    emit '2. Run `bash scripts/zenodo-post-publish.sh <doi1> <doi2> <doi3>`; OpenTimestamps stamp, `ots upgrade` after ~1h.'
    emit '3. Venue lane (separate): PoPETs-2027 (Paper 1), CCS-2026 (Papers 2/3). IACR Paper-1 resubmit needs the rejection ID.'
    ;;
  H)
    emit "## IP — DMCA + patents"
    emit '1. Submit the finalised DMCA at https://github.com/contact/dmca-takedown (perjury statement — YOU only).'
    emit '   Infringer: https://github.com/CYBERELLUM/zipminator-pqc. Notice: docs/ip/dmca-takedown-github.md.'
    emit '2. PCT/priority deadlines (file with Patentstyret/counsel): 2027-03-24, 2027-04-04, 2027-04-05.'
    emit '3. Sync Patent-1 pending files (betalingskvittering etc.) from the other Mac into docs/ip/patent-1-…/filing-2026-03-24/.'
    ;;
  C)
    emit "## Tauri desktop signing"
    emit '1. Install Developer ID Application cert (verify: `security find-identity -v -p codesigning`).'
    emit '2. Set `signingIdentity` in `browser/src-tauri/tauri.conf.json`; export APPLE_ID/APPLE_PASSWORD/APPLE_TEAM_ID.'
    emit '3. `rustup target add x86_64-apple-darwin`; `tauri build --target universal-apple-darwin`; `xcrun stapler staple`.'
    ;;
  Sec)
    emit "## Secret rotation (USER ONLY)"
    emit '- Rotate Supabase anon+service keys; rotate Resend key; DELETE dead `SENDGRID_API_KEY`.'
    emit '- Regenerate OAuth secrets (GitHub/Google/LinkedIn) + `AUTH_SECRET` (`openssl rand -base64 32`).'
    emit '- Rotate root cloud/quantum keys (Anthropic/AWS/IonQ/QBraid/Gemini/OpenRouter/Flask/entropy).'
    emit '- Replace `web/.env -> ../.env` symlink with a web-scoped gitignored `.env.local`.'
    emit '- Review + merge consolidated dependabot PRs.'
    ;;
  *) emit "_No human-gated actions defined for this track; see PROGRAM.yaml human_actions._" ;;
esac

log "wrote $RB"
echo "$RB"
