#!/usr/bin/env bash
# Copies the PUBLIC-SAFE subset of env keys from the root monorepo .env into
# app/.env so Flutter's flutter_dotenv asset bundler picks them up at build time.
#
# Run automatically before `flutter build ipa` / `flutter build appbundle`.
# Idempotent. Safe to run any number of times.
#
# Why this exists: flutter_dotenv reads a literal file path that becomes a
# bundled asset in the IPA / AAB. Symlinks may or may not survive Flutter's
# asset resolver; copy is the deterministic option.
#
# Public-safe = keys that are designed to ship to clients (Supabase ANON key
# is RLS-protected; URL is public). NEVER add SUPABASE_SERVICE_ROLE_KEY,
# AUTH_*_SECRET, or any server-side secret here.

set -euo pipefail

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
APP_DIR="$( cd "${SCRIPT_DIR}/.." && pwd )"
MONOREPO_ROOT="$( cd "${APP_DIR}/../../../.." && pwd )"
ROOT_ENV="${MONOREPO_ROOT}/.env"
APP_ENV="${APP_DIR}/.env"

if [[ ! -f "${ROOT_ENV}" ]]; then
  echo "[sync-env] FATAL: root env not found at ${ROOT_ENV}" >&2
  exit 1
fi

# Public-safe key allowlist. Add new keys here ONLY after confirming they are
# safe to ship in the IPA/AAB (i.e. designed to be client-side public).
PUBLIC_KEYS=(
  SUPABASE_URL
  SUPABASE_ANON_KEY
)

{
  echo "# Auto-generated by app/scripts/sync-env-from-root.sh on $(date '+%Y-%m-%d %H:%M:%S')."
  echo "# Source: ${ROOT_ENV}"
  echo "# DO NOT EDIT BY HAND. DO NOT COMMIT (gitignored)."
  echo "# Public-safe subset only. Server-side secrets stay in root .env."
  echo ""
  for key in "${PUBLIC_KEYS[@]}"; do
    line=$(grep -E "^${key}=" "${ROOT_ENV}" || true)
    if [[ -z "${line}" ]]; then
      echo "[sync-env] WARN: key '${key}' missing from root .env" >&2
      continue
    fi
    echo "${line}"
  done
} > "${APP_ENV}"

count=$(grep -cE "^[A-Z_]+=" "${APP_ENV}" || echo 0)
echo "[sync-env] wrote ${APP_ENV} with ${count} key(s)"
